spring.application.name=blog

# Database connection
spring.datasource.url=jdbc:postgresql://ep-shy-sunset-ahfhte88-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_EFOlUw07gSkf&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EFOlUw07gSkf

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=CK4Y5vBKkZzLEeRdbh2qjfVDybZK9eiYB8APJZ29d8D